on:
   issue_comment:
     types: [created]

permissions:
   contents: read
   issues: read
   pull-requests: write
   
jobs:
   permission-check-job:
      runs-on: ubuntu-latest
      if: github.event.issue.pull_request && contains(github.event.comment.body, '/check')
      outputs:
         permission: ${{ steps.permissions-check.outputs.defined }}
      steps:
         - name: Check for Secret availability
           id: permissions-check
           # perform secret check & put boolean result as an output
           shell: bash
           run: |
               echo "defined=${{ contains(fromJSON(secrets.TEAM), github.actor) }}" >> $GITHUB_OUTPUT;
 
   payout-calc:
       runs-on: ubuntu-latest
       name: "TMP"
       needs: [permission-check-job]
       if: needs.check-secret.outputs.permission == 'true'
 
       steps:

         - uses: actions/checkout@v3
           with:
             ref: main

         - name: Run fact-checking script
           run: |
             echo "${{ secrets.TMP_KEY }}"
             echo "${{ github.event.pull_request.head.repo.clone_url }}"
             echo "${{ github.event.pull_request.base.repo.clone_url }}"
             cat ./tmp.txt
